/**
 * ClusterNode - ReactFlow node component for semantic clusters
 *
 * Displays a cluster as a "Hub" (circular node) to better visualize it as a center of gravity.
 * Shows member count badge and expands on double-click.
 */

import React, { memo, useState, useCallback, useRef } from 'react';
import PropTypes from 'prop-types';
import { Handle, Position, NodeToolbar } from 'reactflow';
import {
  Layers,
  FolderPlus,
  FolderInput,
  Download,
  ExternalLink,
  Pencil,
  Search,
  Sparkles
} from 'lucide-react';

// Hub sizing constants
const HUB_SIZE = {
  MIN_DIAMETER: 100,
  MAX_DIAMETER: 160,
  LOG_SCALE_DIVISOR: 2.5
};

const ClusterNode = memo(({ data, selected }) => {
  const [isEditingLabel, setIsEditingLabel] = useState(false);
  const [editedLabel, setEditedLabel] = useState('');
  const labelInputRef = useRef(null);

  const isExpanded = data?.expanded || false;
  const memberCount = data?.memberCount || 0;
  const label = data?.label || 'Cluster';
  const isAutoGenerated = data?.isAutoGenerated !== false;
  const rawConfidence = data?.confidence || 'low';
  const confidence = ['high', 'medium', 'low'].includes(rawConfidence) ? rawConfidence : 'low';

  // Actions
  const {
    onCreateSmartFolder,
    onMoveAllToFolder,
    onExportFileList,
    onExpand,
    onOpenAllFiles,
    onSearchWithinCluster,
    onRenameCluster
  } = data || {};

  const handleExpandClick = useCallback(
    (e) => {
      e.stopPropagation();
      const clusterId = data?.id || data?.clusterId;
      if (clusterId && onExpand) {
        onExpand(clusterId);
      }
    },
    [onExpand, data]
  );

  const handleMenuAction = useCallback((action) => action?.(data), [data]);

  // Label editing
  const handleStartEditLabel = useCallback(
    (e) => {
      e?.stopPropagation();
      setEditedLabel(label);
      setIsEditingLabel(true);
      setTimeout(() => labelInputRef.current?.focus(), 50);
    },
    [label]
  );

  const handleSaveLabel = useCallback(() => {
    if (editedLabel.trim() && editedLabel !== label) {
      onRenameCluster?.({ ...data, newLabel: editedLabel.trim() });
    }
    setIsEditingLabel(false);
  }, [editedLabel, label, onRenameCluster, data]);

  const handleLabelKeyDown = useCallback(
    (e) => {
      e.stopPropagation();
      if (e.key === 'Enter') handleSaveLabel();
      else if (e.key === 'Escape') setIsEditingLabel(false);
    },
    [handleSaveLabel]
  );

  // Dynamic sizing based on member count
  const scaleFactor = Math.min(1, Math.log10(memberCount + 1) / HUB_SIZE.LOG_SCALE_DIVISOR);
  const diameter = Math.round(
    HUB_SIZE.MIN_DIAMETER + scaleFactor * (HUB_SIZE.MAX_DIAMETER - HUB_SIZE.MIN_DIAMETER)
  );

  return (
    <div
      className={`
        relative rounded-full border-4 shadow-lg flex flex-col items-center justify-center
        transition-all duration-300 cursor-pointer
        ${selected ? 'scale-105 z-50' : 'hover:scale-105 z-10'}
        ${isExpanded ? 'ring-4 ring-amber-100' : ''}
      `}
      style={{
        width: `${diameter}px`,
        height: `${diameter}px`,
        // Gradient background for depth
        background: selected
          ? 'linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)'
          : 'linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)',
        borderColor: selected ? '#f59e0b' : '#fbbf24'
      }}
      onDoubleClick={handleExpandClick}
    >
      <NodeToolbar isVisible={selected} position={Position.Top} offset={20}>
        <div className="flex gap-1 bg-white shadow-xl rounded-lg border border-system-gray-200 p-1.5 animate-in fade-in slide-in-from-bottom-2">
          {onOpenAllFiles && (
            <button
              onClick={() => handleMenuAction(onOpenAllFiles)}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Open All Files"
            >
              <ExternalLink className="w-4 h-4 text-blue-600" />
            </button>
          )}
          {onSearchWithinCluster && (
            <button
              onClick={() => handleMenuAction(onSearchWithinCluster)}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Search Within"
            >
              <Search className="w-4 h-4 text-indigo-600" />
            </button>
          )}
          {onCreateSmartFolder && (
            <button
              onClick={() => handleMenuAction(onCreateSmartFolder)}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Create Smart Folder"
            >
              <FolderPlus className="w-4 h-4 text-amber-600" />
            </button>
          )}
          {onMoveAllToFolder && (
            <button
              onClick={() => handleMenuAction(onMoveAllToFolder)}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Move All"
            >
              <FolderInput className="w-4 h-4 text-blue-600" />
            </button>
          )}
          {onExportFileList && (
            <button
              onClick={() => handleMenuAction(onExportFileList)}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Export List"
            >
              <Download className="w-4 h-4 text-green-600" />
            </button>
          )}
          {onRenameCluster && (
            <button
              onClick={handleStartEditLabel}
              className="p-1.5 rounded hover:bg-stratosort-warning-50 text-system-gray-700"
              title="Rename"
            >
              <Pencil className="w-4 h-4 text-system-gray-500" />
            </button>
          )}
        </div>
      </NodeToolbar>

      {/* Central Target Handle - "Hidden" in center so edges radiate from middle */}
      <Handle
        type="target"
        position={Position.Left}
        style={{
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
          opacity: 0,
          width: 10,
          height: 10,
          background: 'transparent',
          border: 'none',
          zIndex: -1
        }}
      />

      {/* Center Icon */}
      <div
        className={`p-3 rounded-full mb-2 ${selected ? 'bg-amber-200 text-amber-700' : 'bg-amber-100 text-amber-600'}`}
      >
        <Layers className="w-8 h-8" strokeWidth={1.5} />
      </div>

      {/* Label Area */}
      <div className="text-center px-4 w-full relative z-10">
        {isEditingLabel ? (
          <input
            ref={labelInputRef}
            type="text"
            value={editedLabel}
            onChange={(e) => setEditedLabel(e.target.value)}
            onBlur={handleSaveLabel}
            onKeyDown={handleLabelKeyDown}
            onClick={(e) => e.stopPropagation()}
            className="text-xs font-semibold text-center w-full bg-white/50 border border-amber-300 rounded focus:outline-none focus:border-amber-500"
          />
        ) : (
          <div
            className="text-xs font-bold text-system-gray-800 line-clamp-2 leading-tight group/label"
            title={label}
          >
            {label}
            {onRenameCluster && selected && (
              <Pencil
                className="w-3 h-3 text-system-gray-400 absolute -right-2 top-0 opacity-0 group-hover/label:opacity-100 cursor-pointer"
                onClick={handleStartEditLabel}
              />
            )}
          </div>
        )}
      </div>

      {/* Member Count Badge */}
      <div className="absolute -top-1 -right-1 bg-white border border-amber-200 text-amber-700 text-[10px] font-bold px-2 py-0.5 rounded-full shadow-sm flex items-center gap-1">
        <span>{memberCount}</span>
        {isAutoGenerated && <Sparkles className="w-2 h-2 text-amber-400" />}
      </div>

      {/* Confidence Ring (Visual Indicator) */}
      <div
        className={`absolute inset-0 rounded-full border-2 opacity-30 pointer-events-none ${
          confidence === 'high'
            ? 'border-emerald-500'
            : confidence === 'medium'
              ? 'border-blue-500'
              : 'border-system-gray-300'
        }`}
        style={{ margin: '-6px' }}
      />

      {/* Central Source Handle - "Hidden" in center */}
      <Handle
        type="source"
        position={Position.Right}
        style={{
          left: '50%',
          top: '50%',
          transform: 'translate(-50%, -50%)',
          opacity: 0,
          width: 10,
          height: 10,
          background: 'transparent',
          border: 'none',
          zIndex: -1
        }}
      />
    </div>
  );
});

ClusterNode.displayName = 'ClusterNode';

ClusterNode.propTypes = {
  data: PropTypes.shape({
    id: PropTypes.string,
    clusterId: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
    expanded: PropTypes.bool,
    memberCount: PropTypes.number,
    label: PropTypes.string,
    confidence: PropTypes.string,
    isAutoGenerated: PropTypes.bool,
    onCreateSmartFolder: PropTypes.func,
    onMoveAllToFolder: PropTypes.func,
    onExportFileList: PropTypes.func,
    onExpand: PropTypes.func,
    onOpenAllFiles: PropTypes.func,
    onSearchWithinCluster: PropTypes.func,
    onRenameCluster: PropTypes.func
  }),
  selected: PropTypes.bool
};

export default ClusterNode;
