// src/shared/errorCodes.js

const ERROR_CODES = {
  // LLAMA Errors
  LLAMA_MODEL_LOAD_FAILED: 'LLAMA_001',
  LLAMA_MODEL_NOT_FOUND: 'LLAMA_002',
  LLAMA_INFERENCE_FAILED: 'LLAMA_003',
  LLAMA_GPU_ERROR: 'LLAMA_004',
  LLAMA_OOM: 'LLAMA_005',

  // Vector DB Errors
  VECTOR_DB_INIT_FAILED: 'VECTOR_001',
  VECTOR_DB_PERSIST_FAILED: 'VECTOR_002',
  VECTOR_DB_QUERY_FAILED: 'VECTOR_003',
  VECTOR_DB_DIMENSION_MISMATCH: 'VECTOR_004',

  // General Analysis Errors
  EMBEDDING_GENERATION_FAILED: 'EMBED_001',
  ANALYSIS_FAILED: 'ANALYSIS_001',

  // Migration Errors
  MIGRATION_FAILED: 'MIGRATION_001',

  // General Errors
  TIMEOUT: 'GEN_001',
  OPERATION_CANCELLED: 'GEN_002',
  UNKNOWN_ERROR: 'GEN_003',
  QUEUE_FULL: 'GEN_004',
  INVALID_INPUT: 'GEN_005',
  SERVICE_UNAVAILABLE: 'GEN_006'
};

module.exports = { ERROR_CODES };
